name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20

      - name: Release
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release --clean -f ./.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}